[package]
name = "js-regexp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
thiserror = "1.0.43"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
